--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ZzKino/ARQuest
build-by-default: true
branches:
- master
projects:
  ARQuest:
    icon: icon.png
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: 1.3.0
...
